name: dart_ewelink_api
description: An pure dart API to access ewelink services
version: 0.0.5
homepage: https://github.com/ianmaciel/dart_ewelink_api

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  nonce: ^1.2.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.24.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
