name: dart_ewelink_api
description: Pure dart pacakge to access and interact with eWeLink API and services
version: 0.0.5
homepage: https://github.com/ianmaciel/dart_ewelink_api

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  nonce: ^1.2.0
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
